// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Render.MobileCore.Values {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Render.MobileCore.Values.Strings_en_US", typeof(Strings_en_US).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_Zip {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_Zip", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_CreateNewAccount {
            get {
                object obj = ResourceManager.GetObject("Login_CreateNewAccount", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_EmailAddress {
            get {
                object obj = ResourceManager.GetObject("EditContact_EmailAddress", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Assignment {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Assignment", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_ForgotPassword {
            get {
                object obj = ResourceManager.GetObject("Login_ForgotPassword", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_CompanyName {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_CompanyName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PrimaryMenu_Settings {
            get {
                object obj = ResourceManager.GetObject("PrimaryMenu_Settings", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_ContactInformationHeader {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_ContactInformationHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimateRates_Title {
            get {
                object obj = ResourceManager.GetObject("EstimateRates_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Notes {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Notes", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_EmailAddress {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_EmailAddress", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_CurrentTotal {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_CurrentTotal", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_City {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_City", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_EmailAddress {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_EmailAddress", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_Title {
            get {
                object obj = ResourceManager.GetObject("Login_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_ExpirationDate {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_ExpirationDate", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ContactList_Title {
            get {
                object obj = ResourceManager.GetObject("ContactList_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageRates_Title {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageRates_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_CountryCode {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_CountryCode", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Insurance {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Insurance", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_Title {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_FirstName {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_FirstName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_State {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_State", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_MyProfile {
            get {
                object obj = ResourceManager.GetObject("Settings_MyProfile", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_ConfirmPassword {
            get {
                object obj = ResourceManager.GetObject("NewPassword_ConfirmPassword", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_Login {
            get {
                object obj = ResourceManager.GetObject("Login_Login", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Photos {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Photos", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode SetAccountType_EnterPayment {
            get {
                object obj = ResourceManager.GetObject("SetAccountType_EnterPayment", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PrimaryMenu_Estimates {
            get {
                object obj = ResourceManager.GetObject("PrimaryMenu_Estimates", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_Billing {
            get {
                object obj = ResourceManager.GetObject("Settings_Billing", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_Title_Add {
            get {
                object obj = ResourceManager.GetObject("EditContact_Title_Add", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_FirstName {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_FirstName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_Title {
            get {
                object obj = ResourceManager.GetObject("NewPassword_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PrimaryMenu_Logout {
            get {
                object obj = ResourceManager.GetObject("PrimaryMenu_Logout", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_CompanyName {
            get {
                object obj = ResourceManager.GetObject("EditContact_CompanyName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_Title {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Estimates_PhotoGallery {
            get {
                object obj = ResourceManager.GetObject("Estimates_PhotoGallery", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_NameHeader {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_NameHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PanelDetail_Title {
            get {
                object obj = ResourceManager.GetObject("PanelDetail_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_AddressHeader {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_AddressHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_ContactInformationHeader {
            get {
                object obj = ResourceManager.GetObject("EditContact_ContactInformationHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_CountryCode {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_CountryCode", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_StreetAddress2 {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_StreetAddress2", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_Create {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_Create", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_Submit {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_Submit", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_CellPhone {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_CellPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PrimaryMenu_Contacts {
            get {
                object obj = ResourceManager.GetObject("PrimaryMenu_Contacts", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_SecurityNumber {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_SecurityNumber", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode VehicleFillet_Title {
            get {
                object obj = ResourceManager.GetObject("VehicleFillet_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_OtherPhone {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_OtherPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_PasswordManagement {
            get {
                object obj = ResourceManager.GetObject("Settings_PasswordManagement", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddNewUser_Title {
            get {
                object obj = ResourceManager.GetObject("Settings_AddNewUser_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode VehicleType_Title {
            get {
                object obj = ResourceManager.GetObject("VehicleType_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_Zip {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_Zip", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_OtherPhone {
            get {
                object obj = ResourceManager.GetObject("EditContact_OtherPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ContactSearch_Title {
            get {
                object obj = ResourceManager.GetObject("ContactSearch_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_Title_Edit {
            get {
                object obj = ResourceManager.GetObject("EditContact_Title_Edit", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ResetPassword_EmailAddress {
            get {
                object obj = ResourceManager.GetObject("ResetPassword_EmailAddress", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_PrimaryPhone {
            get {
                object obj = ResourceManager.GetObject("EditContact_PrimaryPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_SetNewPassword {
            get {
                object obj = ResourceManager.GetObject("NewPassword_SetNewPassword", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ScanVin_Title {
            get {
                object obj = ResourceManager.GetObject("ScanVin_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_StreetAddress1 {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_StreetAddress1", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_StreetAddress2 {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_StreetAddress2", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_Password {
            get {
                object obj = ResourceManager.GetObject("NewPassword_Password", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_Title {
            get {
                object obj = ResourceManager.GetObject("Settings_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ResetPassword_PhoneNumber {
            get {
                object obj = ResourceManager.GetObject("ResetPassword_PhoneNumber", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_AcceptTermsAndConditions {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_AcceptTermsAndConditions", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddNewUser_AgreeToOwnership {
            get {
                object obj = ResourceManager.GetObject("Settings_AddNewUser_AgreeToOwnership", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageRates_DefaultTaxRate {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageRates_DefaultTaxRate", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_LastName {
            get {
                object obj = ResourceManager.GetObject("EditContact_LastName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_AddressHeader {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_AddressHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_NameHeader {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_NameHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_StreetAddress1 {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_StreetAddress1", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_ExpirationMonth {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_ExpirationMonth", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_PasswordManagement_Password {
            get {
                object obj = ResourceManager.GetObject("Settings_PasswordManagement_Password", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_ExpirationYear {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_ExpirationYear", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_City {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_City", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewContact_Title {
            get {
                object obj = ResourceManager.GetObject("CreateNewContact_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_CellPhone {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_CellPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Vehicle {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Vehicle", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_PasswordManagement_ConfirmPassword {
            get {
                object obj = ResourceManager.GetObject("Settings_PasswordManagement_ConfirmPassword", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode TemporaryPasswordAlert_Title {
            get {
                object obj = ResourceManager.GetObject("TemporaryPasswordAlert_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_NameHeader {
            get {
                object obj = ResourceManager.GetObject("EditContact_NameHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageRates_TaxLabor {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageRates_TaxLabor", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_FirstName {
            get {
                object obj = ResourceManager.GetObject("EditContact_FirstName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_CardType {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_CardType", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_ContactInformationHeader {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_ContactInformationHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode SetAccountType_Title {
            get {
                object obj = ResourceManager.GetObject("SetAccountType_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddNewUser_NewUserEmailAddressConfirm {
            get {
                object obj = ResourceManager.GetObject("Settings_AddNewUser_NewUserEmailAddressConfirm", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddNewUser_Save {
            get {
                object obj = ResourceManager.GetObject("Settings_AddNewUser_Save", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_CreateFullAccount {
            get {
                object obj = ResourceManager.GetObject("NewPassword_CreateFullAccount", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode SetAccountType_StartTrial {
            get {
                object obj = ResourceManager.GetObject("SetAccountType_StartTrial", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_LockEstimate {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_LockEstimate", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_Title {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PrimaryMenu_Feedback {
            get {
                object obj = ResourceManager.GetObject("PrimaryMenu_Feedback", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageRates_DefaultMatrix {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageRates_DefaultMatrix", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_State {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_State", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimateList_ScanVin {
            get {
                object obj = ResourceManager.GetObject("EstimateList_ScanVin", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_ClassificationHeader {
            get {
                object obj = ResourceManager.GetObject("EditContact_ClassificationHeader", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Contacts {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Contacts", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode PaymentMethod_CardNumber {
            get {
                object obj = ResourceManager.GetObject("PaymentMethod_CardNumber", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_Rates {
            get {
                object obj = ResourceManager.GetObject("Settings_Rates", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ResetPassword_ResetPassword {
            get {
                object obj = ResourceManager.GetObject("ResetPassword_ResetPassword", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_CompanyName {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_CompanyName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ResetPassword_Title {
            get {
                object obj = ResourceManager.GetObject("ResetPassword_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EditContact_Classification {
            get {
                object obj = ResourceManager.GetObject("EditContact_Classification", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_EmailEstimate {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_EmailEstimate", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_RatesAndTaxes {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_RatesAndTaxes", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddNewUser_NewUserEmailAddress {
            get {
                object obj = ResourceManager.GetObject("Settings_AddNewUser_NewUserEmailAddress", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode NewPassword_StartTrial {
            get {
                object obj = ResourceManager.GetObject("NewPassword_StartTrial", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_LastName {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_LastName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Operations {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Operations", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_AddUsers {
            get {
                object obj = ResourceManager.GetObject("Settings_AddUsers", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode CreateNewAccount_LastName {
            get {
                object obj = ResourceManager.GetObject("CreateNewAccount_LastName", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Estimates_EstimateList_AddEditPhoto {
            get {
                object obj = ResourceManager.GetObject("Estimates_EstimateList_AddEditPhoto", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode ResetPassword_Code {
            get {
                object obj = ResourceManager.GetObject("ResetPassword_Code", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimateList_Title {
            get {
                object obj = ResourceManager.GetObject("EstimateList_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode EstimatesMenu_Title {
            get {
                object obj = ResourceManager.GetObject("EstimatesMenu_Title", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageProfile_OtherPhone {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageProfile_OtherPhone", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_Username {
            get {
                object obj = ResourceManager.GetObject("Login_Username", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Login_Password {
            get {
                object obj = ResourceManager.GetObject("Login_Password", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
        
        public static System.Resources.ResXDataNode Settings_ManageRates_DefaultLaborRate {
            get {
                object obj = ResourceManager.GetObject("Settings_ManageRates_DefaultLaborRate", resourceCulture);
                return ((System.Resources.ResXDataNode)(obj));
            }
        }
    }
}
