// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Render.MobileCore.Values {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Render.MobileCore.Values.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Settings_ManageProfile_Zip {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_Zip", resourceCulture);
            }
        }
        
        public static string Login_CreateNewAccount {
            get {
                return ResourceManager.GetString("Login_CreateNewAccount", resourceCulture);
            }
        }
        
        public static string EditContact_EmailAddress {
            get {
                return ResourceManager.GetString("EditContact_EmailAddress", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_ScanVin {
            get {
                return ResourceManager.GetString("AddEditVehicle_ScanVin", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Assignment {
            get {
                return ResourceManager.GetString("EstimatesMenu_Assignment", resourceCulture);
            }
        }
        
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_CompanyName {
            get {
                return ResourceManager.GetString("CreateNewAccount_CompanyName", resourceCulture);
            }
        }
        
        public static string PrimaryMenu_Settings {
            get {
                return ResourceManager.GetString("PrimaryMenu_Settings", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_ContactInformationHeader {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_ContactInformationHeader", resourceCulture);
            }
        }
        
        public static string EstimateRates_Title {
            get {
                return ResourceManager.GetString("EstimateRates_Title", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Notes {
            get {
                return ResourceManager.GetString("EstimatesMenu_Notes", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_EmailAddress {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_EmailAddress", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_CurrentTotal {
            get {
                return ResourceManager.GetString("EstimatesMenu_CurrentTotal", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_City {
            get {
                return ResourceManager.GetString("CreateNewAccount_City", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_EmailAddress {
            get {
                return ResourceManager.GetString("CreateNewAccount_EmailAddress", resourceCulture);
            }
        }
        
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        public static string PaymentMethod_ExpirationDate {
            get {
                return ResourceManager.GetString("PaymentMethod_ExpirationDate", resourceCulture);
            }
        }
        
        public static string ContactList_Title {
            get {
                return ResourceManager.GetString("ContactList_Title", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_Title {
            get {
                return ResourceManager.GetString("Settings_ManageRates_Title", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_CountryCode {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_CountryCode", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Insurance {
            get {
                return ResourceManager.GetString("EstimatesMenu_Insurance", resourceCulture);
            }
        }
        
        public static string PaymentMethod_Title {
            get {
                return ResourceManager.GetString("PaymentMethod_Title", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_FirstName {
            get {
                return ResourceManager.GetString("CreateNewAccount_FirstName", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_State {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_State", resourceCulture);
            }
        }
        
        public static string Settings_MyProfile {
            get {
                return ResourceManager.GetString("Settings_MyProfile", resourceCulture);
            }
        }
        
        public static string NewPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Photos {
            get {
                return ResourceManager.GetString("EstimatesMenu_Photos", resourceCulture);
            }
        }
        
        public static string SetAccountType_EnterPayment {
            get {
                return ResourceManager.GetString("SetAccountType_EnterPayment", resourceCulture);
            }
        }
        
        public static string PrimaryMenu_Estimates {
            get {
                return ResourceManager.GetString("PrimaryMenu_Estimates", resourceCulture);
            }
        }
        
        public static string Settings_Billing {
            get {
                return ResourceManager.GetString("Settings_Billing", resourceCulture);
            }
        }
        
        public static string EditContact_Title_Add {
            get {
                return ResourceManager.GetString("EditContact_Title_Add", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_FirstName {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_FirstName", resourceCulture);
            }
        }
        
        public static string NewPassword_Title {
            get {
                return ResourceManager.GetString("NewPassword_Title", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_VehicleType {
            get {
                return ResourceManager.GetString("Settings_ManageRates_VehicleType", resourceCulture);
            }
        }
        
        public static string PrimaryMenu_Logout {
            get {
                return ResourceManager.GetString("PrimaryMenu_Logout", resourceCulture);
            }
        }
        
        public static string EditContact_CompanyName {
            get {
                return ResourceManager.GetString("EditContact_CompanyName", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_Title {
            get {
                return ResourceManager.GetString("CreateNewAccount_Title", resourceCulture);
            }
        }
        
        public static string Estimates_PhotoGallery {
            get {
                return ResourceManager.GetString("Estimates_PhotoGallery", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Vin {
            get {
                return ResourceManager.GetString("AddEditVehicle_Vin", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_NameHeader {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_NameHeader", resourceCulture);
            }
        }
        
        public static string PanelDetail_Title {
            get {
                return ResourceManager.GetString("PanelDetail_Title", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_AddressHeader {
            get {
                return ResourceManager.GetString("CreateNewAccount_AddressHeader", resourceCulture);
            }
        }
        
        public static string EditContact_ContactInformationHeader {
            get {
                return ResourceManager.GetString("EditContact_ContactInformationHeader", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_CountryCode {
            get {
                return ResourceManager.GetString("CreateNewAccount_CountryCode", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_StreetAddress2 {
            get {
                return ResourceManager.GetString("CreateNewAccount_StreetAddress2", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Make {
            get {
                return ResourceManager.GetString("AddEditVehicle_Make", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_Create {
            get {
                return ResourceManager.GetString("CreateNewAccount_Create", resourceCulture);
            }
        }
        
        public static string PaymentMethod_Submit {
            get {
                return ResourceManager.GetString("PaymentMethod_Submit", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_CellPhone {
            get {
                return ResourceManager.GetString("CreateNewAccount_CellPhone", resourceCulture);
            }
        }
        
        public static string PrimaryMenu_Contacts {
            get {
                return ResourceManager.GetString("PrimaryMenu_Contacts", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Model {
            get {
                return ResourceManager.GetString("AddEditVehicle_Model", resourceCulture);
            }
        }
        
        public static string PaymentMethod_SecurityNumber {
            get {
                return ResourceManager.GetString("PaymentMethod_SecurityNumber", resourceCulture);
            }
        }
        
        public static string VehicleFillet_Title {
            get {
                return ResourceManager.GetString("VehicleFillet_Title", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_OtherPhone {
            get {
                return ResourceManager.GetString("CreateNewAccount_OtherPhone", resourceCulture);
            }
        }
        
        public static string Settings_PasswordManagement {
            get {
                return ResourceManager.GetString("Settings_PasswordManagement", resourceCulture);
            }
        }
        
        public static string Settings_AddNewUser_Title {
            get {
                return ResourceManager.GetString("Settings_AddNewUser_Title", resourceCulture);
            }
        }
        
        public static string VehicleType_Title {
            get {
                return ResourceManager.GetString("VehicleType_Title", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_Zip {
            get {
                return ResourceManager.GetString("CreateNewAccount_Zip", resourceCulture);
            }
        }
        
        public static string EditContact_OtherPhone {
            get {
                return ResourceManager.GetString("EditContact_OtherPhone", resourceCulture);
            }
        }
        
        public static string ContactSearch_Title {
            get {
                return ResourceManager.GetString("ContactSearch_Title", resourceCulture);
            }
        }
        
        public static string EditContact_Title_Edit {
            get {
                return ResourceManager.GetString("EditContact_Title_Edit", resourceCulture);
            }
        }
        
        public static string ResetPassword_EmailAddress {
            get {
                return ResourceManager.GetString("ResetPassword_EmailAddress", resourceCulture);
            }
        }
        
        public static string EditContact_PrimaryPhone {
            get {
                return ResourceManager.GetString("EditContact_PrimaryPhone", resourceCulture);
            }
        }
        
        public static string NewPassword_SetNewPassword {
            get {
                return ResourceManager.GetString("NewPassword_SetNewPassword", resourceCulture);
            }
        }
        
        public static string ScanVin_Title {
            get {
                return ResourceManager.GetString("ScanVin_Title", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_StreetAddress1 {
            get {
                return ResourceManager.GetString("CreateNewAccount_StreetAddress1", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_StreetAddress2 {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_StreetAddress2", resourceCulture);
            }
        }
        
        public static string NewPassword_Password {
            get {
                return ResourceManager.GetString("NewPassword_Password", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword_PhoneNumber", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_AcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("CreateNewAccount_AcceptTermsAndConditions", resourceCulture);
            }
        }
        
        public static string Settings_AddNewUser_AgreeToOwnership {
            get {
                return ResourceManager.GetString("Settings_AddNewUser_AgreeToOwnership", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_DefaultTaxRate {
            get {
                return ResourceManager.GetString("Settings_ManageRates_DefaultTaxRate", resourceCulture);
            }
        }
        
        public static string EditContact_LastName {
            get {
                return ResourceManager.GetString("EditContact_LastName", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_AddressHeader {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_AddressHeader", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_NameHeader {
            get {
                return ResourceManager.GetString("CreateNewAccount_NameHeader", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_StreetAddress1 {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_StreetAddress1", resourceCulture);
            }
        }
        
        public static string PaymentMethod_ExpirationMonth {
            get {
                return ResourceManager.GetString("PaymentMethod_ExpirationMonth", resourceCulture);
            }
        }
        
        public static string Settings_PasswordManagement_Password {
            get {
                return ResourceManager.GetString("Settings_PasswordManagement_Password", resourceCulture);
            }
        }
        
        public static string PaymentMethod_ExpirationYear {
            get {
                return ResourceManager.GetString("PaymentMethod_ExpirationYear", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_City {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_City", resourceCulture);
            }
        }
        
        public static string CreateNewContact_Title {
            get {
                return ResourceManager.GetString("CreateNewContact_Title", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_CellPhone {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_CellPhone", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Vehicle {
            get {
                return ResourceManager.GetString("EstimatesMenu_Vehicle", resourceCulture);
            }
        }
        
        public static string Settings_PasswordManagement_ConfirmPassword {
            get {
                return ResourceManager.GetString("Settings_PasswordManagement_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Color {
            get {
                return ResourceManager.GetString("AddEditVehicle_Color", resourceCulture);
            }
        }
        
        public static string TemporaryPasswordAlert_Title {
            get {
                return ResourceManager.GetString("TemporaryPasswordAlert_Title", resourceCulture);
            }
        }
        
        public static string EditContact_NameHeader {
            get {
                return ResourceManager.GetString("EditContact_NameHeader", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_TaxLabor {
            get {
                return ResourceManager.GetString("Settings_ManageRates_TaxLabor", resourceCulture);
            }
        }
        
        public static string EditContact_FirstName {
            get {
                return ResourceManager.GetString("EditContact_FirstName", resourceCulture);
            }
        }
        
        public static string PaymentMethod_CardType {
            get {
                return ResourceManager.GetString("PaymentMethod_CardType", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_ContactInformationHeader {
            get {
                return ResourceManager.GetString("CreateNewAccount_ContactInformationHeader", resourceCulture);
            }
        }
        
        public static string SetAccountType_Title {
            get {
                return ResourceManager.GetString("SetAccountType_Title", resourceCulture);
            }
        }
        
        public static string Settings_AddNewUser_NewUserEmailAddressConfirm {
            get {
                return ResourceManager.GetString("Settings_AddNewUser_NewUserEmailAddressConfirm", resourceCulture);
            }
        }
        
        public static string Settings_AddNewUser_Save {
            get {
                return ResourceManager.GetString("Settings_AddNewUser_Save", resourceCulture);
            }
        }
        
        public static string NewPassword_CreateFullAccount {
            get {
                return ResourceManager.GetString("NewPassword_CreateFullAccount", resourceCulture);
            }
        }
        
        public static string SetAccountType_StartTrial {
            get {
                return ResourceManager.GetString("SetAccountType_StartTrial", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_LockEstimate {
            get {
                return ResourceManager.GetString("EstimatesMenu_LockEstimate", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_Title {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_Title", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Stock {
            get {
                return ResourceManager.GetString("AddEditVehicle_Stock", resourceCulture);
            }
        }
        
        public static string PrimaryMenu_Feedback {
            get {
                return ResourceManager.GetString("PrimaryMenu_Feedback", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_DefaultMatrix {
            get {
                return ResourceManager.GetString("Settings_ManageRates_DefaultMatrix", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_State {
            get {
                return ResourceManager.GetString("CreateNewAccount_State", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_JobNumber {
            get {
                return ResourceManager.GetString("AddEditVehicle_JobNumber", resourceCulture);
            }
        }
        
        public static string EstimateList_ScanVin {
            get {
                return ResourceManager.GetString("EstimateList_ScanVin", resourceCulture);
            }
        }
        
        public static string EditContact_ClassificationHeader {
            get {
                return ResourceManager.GetString("EditContact_ClassificationHeader", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Contacts {
            get {
                return ResourceManager.GetString("EstimatesMenu_Contacts", resourceCulture);
            }
        }
        
        public static string PaymentMethod_CardNumber {
            get {
                return ResourceManager.GetString("PaymentMethod_CardNumber", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Plate {
            get {
                return ResourceManager.GetString("AddEditVehicle_Plate", resourceCulture);
            }
        }
        
        public static string Settings_Rates {
            get {
                return ResourceManager.GetString("Settings_Rates", resourceCulture);
            }
        }
        
        public static string ResetPassword_ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword_ResetPassword", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_CompanyName {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_CompanyName", resourceCulture);
            }
        }
        
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        public static string EditContact_Classification {
            get {
                return ResourceManager.GetString("EditContact_Classification", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_EmailEstimate {
            get {
                return ResourceManager.GetString("EstimatesMenu_EmailEstimate", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_RatesAndTaxes {
            get {
                return ResourceManager.GetString("EstimatesMenu_RatesAndTaxes", resourceCulture);
            }
        }
        
        public static string Settings_AddNewUser_NewUserEmailAddress {
            get {
                return ResourceManager.GetString("Settings_AddNewUser_NewUserEmailAddress", resourceCulture);
            }
        }
        
        public static string NewPassword_StartTrial {
            get {
                return ResourceManager.GetString("NewPassword_StartTrial", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_LastName {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_LastName", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Operations {
            get {
                return ResourceManager.GetString("EstimatesMenu_Operations", resourceCulture);
            }
        }
        
        public static string Settings_AddUsers {
            get {
                return ResourceManager.GetString("Settings_AddUsers", resourceCulture);
            }
        }
        
        public static string AddEditVehicle_Year {
            get {
                return ResourceManager.GetString("AddEditVehicle_Year", resourceCulture);
            }
        }
        
        public static string CreateNewAccount_LastName {
            get {
                return ResourceManager.GetString("CreateNewAccount_LastName", resourceCulture);
            }
        }
        
        public static string Estimates_EstimateList_AddEditPhoto {
            get {
                return ResourceManager.GetString("Estimates_EstimateList_AddEditPhoto", resourceCulture);
            }
        }
        
        public static string ResetPassword_Code {
            get {
                return ResourceManager.GetString("ResetPassword_Code", resourceCulture);
            }
        }
        
        public static string EstimateList_Title {
            get {
                return ResourceManager.GetString("EstimateList_Title", resourceCulture);
            }
        }
        
        public static string EstimatesMenu_Title {
            get {
                return ResourceManager.GetString("EstimatesMenu_Title", resourceCulture);
            }
        }
        
        public static string Settings_ManageProfile_OtherPhone {
            get {
                return ResourceManager.GetString("Settings_ManageProfile_OtherPhone", resourceCulture);
            }
        }
        
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        public static string Settings_ManageRates_DefaultLaborRate {
            get {
                return ResourceManager.GetString("Settings_ManageRates_DefaultLaborRate", resourceCulture);
            }
        }
    }
}
